#Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem

print('resposta usando "for" ')
base = int(input('base: '))
expoente = int(input('expoente: '))
print()
resultado = 1
for v in range(expoente):
    resultado = resultado*base 
print(f"""RESPOSTAS :
{base} ^ {expoente} = {resultado}""")
